### ISSUE TITLE
Some suggestions/feedback

### ISSUE THREAD

**Issue by MaikuB** [bizz84/firebase_auth_demo_flutter#16]
Thanks for sharing the repository for others to refer to. Had a couple of suggestions that could be looked into

- Rather than splitting your build methods into smaller methods, split them into smaller widgets. See this article for more info https://iirokrankka.com/2018/12/11/splitting-widgets-to-methods-performance-antipattern/
- Instead of pulling in separate libraries for google and facebook sign in, I suspect you'd be able to use the AppAuth wrapper I've written https://github.com/MaikuB/flutter_appauth. This isn't attempt to plug my plugin but more to do with simplifying the dependencies. A maintainer of the AppAuth Android SDK has a sample Android application that connects to both identity providers at https://github.com/iainmcgin/AppAuth-Demo

**Comment by bizz84** [comment]
Good suggestions.
Yes, classes are better than methods for widgets.
Currently this is done in some places, and not others.
E.g. I just added a `AuthServiceTypeSelector` widget, which was previously a method in `DeveloperMenu`.
`SignInPage` and `EmailPasswordSignInPage` are quite big and could also get a similar treatment.
Sometimes it's a tradeoff between doing the right thing and more boilerplate code ;)

Re. auth wrapper - it's a good effort on your side. As this is a reference implementation I prefer to use official packages only.
