### ISSUE TITLE
Google SignIn do not Work

### ISSUE THREAD

**Issue by SaputraGo** [bizz84/firebase_auth_demo_flutter#18]
error 
`Exception has occurred.
PlatformException (PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null))`

please resolve this problem

**Comment by bizz84** [comment]
This is most likely a Firebase configuration issue on your end.

Make sure you follow the instructions for setting up Google sign-in on your target platform:

https://github.com/bizz84/firebase_auth_demo_flutter#running-the-project-with-firebase

**Comment by bizz84** [comment]
@SaputraGo I'm closing this but feel free to open a new issue if you still have problems.
