### ISSUE TITLE
Android Stuck on installing...

### ISSUE THREAD

**Issue by springfitnesstechnology** [bizz84/firebase_auth_demo_flutter#21]
I followed the instructions for the setup, but when I try to build the app in android it gets stuck on "Installing build/app/outputs/apk/app.apk". You can see it try to open the app, but it immediately crashes. The last output of the debug console is "Built build/app/outputs/apk/debug/app-debug.apk.".

The iOS version runs fine.

**Comment by springfitnesstechnology** [comment]
Update: I just went through the Udemy course, and it works up until the "Managing and Updating Package" section. I'm going through the videos now to see where it goes wrong.

**Comment by springfitnesstechnology** [comment]
I think this was probably an issue with the packages. I followed the Udemy course and was able to fix it.

**Comment by rogueturnip** [comment]
Just in case anyone looks at this, I had the same issue and noticed it was a Dex issues.  I added multidex support and it started up.
