### ISSUE TITLE
how do you add multiple provider

### ISSUE THREAD

**Issue by premtemp1** [bizz84/firebase_auth_demo_flutter#22]
Hello,
  Thanks for the article... How do you add multiple provider,,, Suppose , I have another provider name shopping that I also need down stream...

Thanks

**Comment by bizz84** [comment]
@premtemp1 sorry for the late reply.

One way to do this is to use a [MultiProvider](https://github.com/rrousselGit/provider#multiprovider)

Example:

```dart
MultiProvider(
  providers: [
    Provider<Foo>.value(value: foo),
    Provider<Bar>.value(value: bar),
    Provider<Baz>.value(value: baz),
  ],
  child: someWidget,
)
```

Another example is the current `main.dart` file:

https://github.com/bizz84/firebase_auth_demo_flutter/blob/master/lib/main.dart

Hope this helps.
