### ISSUE TITLE
Question: Standalone library

### ISSUE THREAD

**Issue by jon301** [bizz84/firebase_auth_demo_flutter#26]
Hi @bizz84,

Thank you for your work, this auth implementation with Provider looks neat !
I'd love to use it in my project and I was wondering if you've planned to publish a standalone library for ease of use ?

J.

**Comment by bizz84** [comment]
I thought about it, but I decided against it.

The main reason is that this is a reference implementation.

It makes some assumptions about:

- how the sign in screens should look like
- how the AuthService class should work
- how dependencies should be accessed (Provider)

and more.

I'd much rather let people pick and choose the bits they like, and change the bits they want.
