### ISSUE TITLE
'archivedDataWithRootObject:requiringSecureCoding:error:'

### ISSUE THREAD

**Issue by yasinarik** [bizz84/firebase_auth_demo_flutter#35]
- Created a new Flutter Project. Built it and run for the first time. Then exited.
- I've created a Firebase project and successfully set bundle id.  
- Added the GoogleService-Info.plist file into the place.
- I copied the lib folder and pubspec.yaml files from your "amazing :)"  repo and replaced the new flutter project files.

It can't build the app now :(

**Error Code**

FolderOfTheApp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTLibrary/GDTStorage.m:122:41: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
            NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self

**Flutter Doctor**
`[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.2 17C88, locale en-TR)
    • Flutter version 1.9.1+hotfix.2 at /Users/yasinarik/Documents/flutter
    • Framework revision 2d2a1ffec9 (9 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yasinarik/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone 8 • C0922638-B946-421B-BE90-C8D92A6B475F • ios • iOS 11.4 (simulator)

• No issues found!`

**Comment by bizz84** [comment]
@yasinarik A couple of things worth noting:

- Your pod repo may be updated. Have you tried running `pod repo update`?
- You're running on Xcode 9.4.1. Have you tried updating to Xcode 10 or 11?

Let me know if any of these fixes your problem.
