### ISSUE TITLE
Logout don't rebuild UI

### ISSUE THREAD

**Issue by alexdess** [bizz84/firebase_auth_demo_flutter#76]
Hello,

I'm integrating your authentification workflow on my project.
It doesn't work when I do a logout, the builder don't rebuild the UI.
It works when I use "login" or "logout" functions.

In my example (see picture, RootPage is not rebuild)
I tried to fix it but I am not able to do it.
![image](https://user-images.githubusercontent.com/8177780/110253330-0faad380-7f8a-11eb-8300-14ba4d20a578.png)

**Comment by Abacaxi-Nelson** [comment]
It happen to me also.. i have to navigator.pop and the logout.. seems related to the number of page pushed to hsitory

**Comment by alexdess** [comment]
Personally I do not use the navigator in my app. I will however set it up as a workaround for this problem.

**Comment by alexdess** [comment]
Hello, finally I found what was wrong.
When the stream Stream<MyAppUser?> get onAuthStateChanged  receveid null (in case of logout for example)
the builder is not recalled. I change the code like that:

![image](https://user-images.githubusercontent.com/8177780/110598645-45b2a800-8182-11eb-9dc4-805dda345b17.png)

and the AuthWidget
![image](https://user-images.githubusercontent.com/8177780/110599086-cd001b80-8182-11eb-8f71-c6d9e1cff371.png)

I think the repo should be adapted accordingly.
